### ISSUE TITLE
Instagram responded with HTTP error 429.

### ISSUE THREAD

**Issue by Diglee147** [amitupreti/Instagram-Follower-Scraper#9]
It works for +- 180 contacts, then it stop working for instagram captcha on Cellphone for a proof that is me, so when i tryied again, it worked for +-180 contacts again, but now, when i try again, all the time i receive the message: Too many requests.

How can i solve?

![image](https://user-images.githubusercontent.com/97317367/153891900-d03a2407-d8ec-4f08-b43a-edd068aebe39.png)

**Comment by FLASHY4** [comment]
Hi,
I still have the same problem
Any solution?
